name: Continuos Integration
on:
  pull_request:

jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: NodeJS 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn/v6
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependecies
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Linting
        run: yarn run lint
