name: Integration
on:
  pull_request:

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: NodeJS 10.x
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: Cache dependecies
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn/v6
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependecies
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Linting
        run: yarn run lint

    timeout-minutes: 5 #if need we can increment it
