name: Continuos Deploy
on:
  # push:
  #   branches:
  #     - master
  release:
    types:
      - created

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: NodeJS 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Cache dependecies
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn/v6
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependecies
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Linting
        run: yarn run lint

      # Used for Firebase
      - name: Build for production
        run: yarn run build:prod

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      #
      #
      # Used for GitHub Pages
      # - name: Build for production
      #   run: yarn run build:prod --base-href /test-github-actions/
      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./dist/ng-github-actions
